name: add-new-schools
on:
  workflow_dispatch:
    inputs:
      school_name:
        description: 'Tên trường'
        required: true
      school_url:
        description: 'Website trường'
        required: true
      school_level:
        description: 'Cấp học'
        required: true
        type: choice
        options: 
        - THCS
        - THPT
      district_id:
        description: 'Mã quận/huyện'
        required: true
        type: number


jobs:
  add-new-schools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i
      - run: npm run add-school -- "${{ github.event.inputs.school_name }}" "${{ github.event.inputs.school_level }}" "${{ github.event.inputs.district_id }}"
      - run: npm run validate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add new school
          title: Bổ sung trường ${{ github.event.inputs.school_name }}
          body: |
            Cập nhật trường ${{ github.event.inputs.school_name }}
            - Website: ${{ github.event.inputs.school_url }}
            - Cấp học: ${{ github.event.inputs.school_level }}
            - Mã quận/huyện: ${{ github.event.inputs.district_id }}
          branch: add-new-school
          branch-suffix: timestamp
          delete-branch: true
