name: validate
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  push:
    branches:
      - main
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i
      - run: npm run validate
      # Fail the CI if git diff found any changes
      - run: git diff --exit-code
